name: Model Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test GraphicsCards
        run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName~Test_OptimumTech.Tests.GraphicsCardsTests*"

      - name: Test Processors
        run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName~Test_OptimumTech.Tests.ProcessorsTests*"

      - name: Test Orders
        run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName~Test_OptimumTech.Tests.OrderTest*"

      - name: Test Users
        run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName~Test_OptimumTech.Tests.UserTests*"

      - name: Test Products
        run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName~Test_OptimumTech.Tests.ProductTests*"
